# Generated by Django 4.2.9 on 2024-02-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('popularity', models.PositiveIntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
